### LOGIN ADMIN
POST http://localhost:8000/api/login
Content-Type: application/json

{
  "email": "admin@email.com",
  "password": "admin123"
}

### LOGIN USUAL
POST http://localhost:8000/api/login
Content-Type: application/json

{
  "email": "user@email.com",
  "password": "user123"
}

### CRIAR CONTATO (ADMIN)
POST http://localhost:8000/api/contacts
Authorization: Bearer 1|qQpGa9E3vJEfxNUW5BRBedkmQNAClZ3QfSM0LxZR1f6621cf
Content-Type: application/json

{
  "name": "Maria Santos",
  "description": "Cliente Premium",
  "address": {
    "zip_code": "20040-007",
    "address_number": "123",
    "country": "Brasil"
  },
  "phones": [
    { "phone": "(21) 98888-8888" }
  ],
  "emails": [
    { "email": "maria@email.com" }
  ]
}

### LISTAR CONTATOS (ADMIN)
GET http://localhost:8000/api/contacts
Authorization: Bearer 1|qQpGa9E3vJEfxNUW5BRBedkmQNAClZ3QfSM0LxZR1f6621cf

### DADOS DO USUÁRIO LOGADO
GET http://localhost:8000/api/me
Authorization: Bearer 1|qQpGa9E3vJEfxNUW5BRBedkmQNAClZ3QfSM0LxZR1f6621cf

### ATUALIZAR CONTATO (ADMIN)
PUT http://localhost:8000/api/contacts/1
Authorization: Bearer 1|qQpGa9E3vJEfxNUW5BRBedkmQNAClZ3QfSM0LxZR1f6621cf
Content-Type: application/json

{
  "name": "Maria Santos Silva",
  "description": "Cliente Premium Atualizado",
  "address": {
    "zip_code": "01310-100",
    "address_number": "500",
    "country": "Brasil"
  },
  "phones": [
    { "phone": "(11) 96666-6666" }
  ],
  "emails": [
    { "email": "maria.silva@email.com" }
  ]
}

### DELETAR CONTATO (ADMIN)
DELETE http://localhost:8000/api/contacts/1
Authorization: Bearer 1|qQpGa9E3vJEfxNUW5BRBedkmQNAClZ3QfSM0LxZR1f6621cf

### LOGOUT
POST http://localhost:8000/api/logout
Authorization: Bearer 1|qQpGa9E3vJEfxNUW5BRBedkmQNAClZ3QfSM0LxZR1f6621cf

### CRIAR CONTATO COM CEP INVÁLIDO
POST http://localhost:8000/api/contacts
Authorization: Bearer 1|qQpGa9E3vJEfxNUW5BRBedkmQNAClZ3QfSM0LxZR1f6621cf
Content-Type: application/json

{
  "name": "Teste CEP Inválido",
  "description": "Teste",
  "address": {
    "zip_code": "00000-000",
    "address_number": "123",
    "country": "Brasil"
  },
  "phones": [
    { "phone": "(11) 99999-9999" }
  ],
  "emails": [
    { "email": "teste@email.com" }
  ]
}

### CRIAR CONTATO COM CAMPOS OBRIGATÓRIOS FALTANDO
POST http://localhost:8000/api/contacts
Authorization: Bearer 1|qQpGa9E3vJEfxNUW5BRBedkmQNAClZ3QfSM0LxZR1f6621cf
Content-Type: application/json

{
  "description": "Faltando nome",
  "address": {
    "zip_code": "01001-000",
    "address_number": "10",
    "country": "Brasil"
  },
  "phones": [
    { "phone": "(11) 90000-0000" }
  ],
  "emails": [
    { "email": "joao@email.com" }
  ]
}
